[2023-02-26 16:00:32,989] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T15:59:00+00:00 [queued]>
[2023-02-26 16:00:32,995] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T15:59:00+00:00 [queued]>
[2023-02-26 16:00:32,995] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 16:00:32,996] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2023-02-26 16:00:32,996] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 16:00:33,006] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): taxi_api_to_db> on 2023-02-26 15:59:00+00:00
[2023-02-26 16:00:33,012] {standard_task_runner.py:52} INFO - Started process 10273 to run task
[2023-02-26 16:00:33,015] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_taxi_availability', 'taxi_api_to_db', 'scheduled__2023-02-26T15:59:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/get_taxi_availability.py', '--cfg-path', '/tmp/tmp1xqh_knu', '--error-file', '/tmp/tmplbzz_nuq']
[2023-02-26 16:00:33,016] {standard_task_runner.py:80} INFO - Job 108: Subtask taxi_api_to_db
[2023-02-26 16:00:33,026] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-02-26 16:00:33,058] {task_command.py:370} INFO - Running <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T15:59:00+00:00 [running]> on host 0337baec7fd8
[2023-02-26 16:00:33,110] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_taxi_availability
AIRFLOW_CTX_TASK_ID=taxi_api_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-26T15:59:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-26T15:59:00+00:00
[2023-02-26 16:00:33,955] {logging_mixin.py:115} INFO - Succesful connection with API.
[2023-02-26 16:00:33,956] {logging_mixin.py:115} INFO - -------------------------------
[2023-02-26 16:00:33,959] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/taxi_availability.py", line 82, in run_taxi_api_to_db
    etl.transform()
  File "/opt/airflow/dags/functions/taxi_availability.py", line 51, in transform
    df1 = json_normalize(df,'features')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_normalize.py", line 504, in _json_normalize
    _recursive_extract(data, record_path, {}, level=0)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_normalize.py", line 477, in _recursive_extract
    recs = _pull_records(obj, path[0])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_normalize.py", line 399, in _pull_records
    result = _pull_field(js, spec)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_normalize.py", line 390, in _pull_field
    result = result[spec]
TypeError: string indices must be integers
[2023-02-26 16:00:33,968] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=get_taxi_availability, task_id=taxi_api_to_db, execution_date=20230226T155900, start_date=20230226T160032, end_date=20230226T160033
[2023-02-26 16:00:33,978] {standard_task_runner.py:97} ERROR - Failed to execute job 108 for task taxi_api_to_db (string indices must be integers; 10273)
[2023-02-26 16:00:33,994] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-26 16:00:34,022] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
