[2023-02-26 13:36:42,418] {processor.py:153} INFO - Started process (PID=3148) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:36:42,419] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:36:42,420] {logging_mixin.py:115} INFO - [2023-02-26 13:36:42,420] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:36:42,779] {logging_mixin.py:115} INFO - [2023-02-26 13:36:42,773] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 9, in <module>
    from helpers.helper import pg_to_df, query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:36:42,782] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:36:42,793] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.377 seconds
[2023-02-26 13:37:02,650] {processor.py:153} INFO - Started process (PID=3170) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:02,650] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:37:02,651] {logging_mixin.py:115} INFO - [2023-02-26 13:37:02,651] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:02,974] {logging_mixin.py:115} INFO - [2023-02-26 13:37:02,969] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:37:02,976] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:02,987] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.340 seconds
[2023-02-26 13:37:07,357] {processor.py:153} INFO - Started process (PID=3174) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:07,357] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:37:07,358] {logging_mixin.py:115} INFO - [2023-02-26 13:37:07,358] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:07,706] {logging_mixin.py:115} INFO - [2023-02-26 13:37:07,697] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:37:07,708] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:07,733] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.379 seconds
[2023-02-26 13:37:28,939] {processor.py:153} INFO - Started process (PID=3195) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:28,939] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:37:28,940] {logging_mixin.py:115} INFO - [2023-02-26 13:37:28,940] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:29,249] {logging_mixin.py:115} INFO - [2023-02-26 13:37:29,244] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:37:29,251] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:29,263] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.327 seconds
[2023-02-26 13:37:32,977] {processor.py:153} INFO - Started process (PID=3207) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:32,978] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:37:32,978] {logging_mixin.py:115} INFO - [2023-02-26 13:37:32,978] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:33,301] {logging_mixin.py:115} INFO - [2023-02-26 13:37:33,292] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:37:33,304] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:33,327] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.352 seconds
[2023-02-26 13:37:44,423] {processor.py:153} INFO - Started process (PID=3221) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:44,423] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:37:44,424] {logging_mixin.py:115} INFO - [2023-02-26 13:37:44,424] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:44,725] {logging_mixin.py:115} INFO - [2023-02-26 13:37:44,720] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:37:44,728] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:37:44,741] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.320 seconds
[2023-02-26 13:38:14,950] {processor.py:153} INFO - Started process (PID=3244) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:14,950] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:38:14,951] {logging_mixin.py:115} INFO - [2023-02-26 13:38:14,951] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:15,304] {logging_mixin.py:115} INFO - [2023-02-26 13:38:15,293] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:38:15,306] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:15,324] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.377 seconds
[2023-02-26 13:38:16,027] {processor.py:153} INFO - Started process (PID=3246) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:16,028] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:38:16,030] {logging_mixin.py:115} INFO - [2023-02-26 13:38:16,030] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:16,322] {logging_mixin.py:115} INFO - [2023-02-26 13:38:16,316] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:38:16,323] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:16,337] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.315 seconds
[2023-02-26 13:38:29,449] {processor.py:153} INFO - Started process (PID=3266) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:29,449] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:38:29,450] {logging_mixin.py:115} INFO - [2023-02-26 13:38:29,450] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:29,726] {logging_mixin.py:115} INFO - [2023-02-26 13:38:29,721] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:38:29,728] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:29,739] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.292 seconds
[2023-02-26 13:38:33,494] {processor.py:153} INFO - Started process (PID=3268) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:33,495] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:38:33,496] {logging_mixin.py:115} INFO - [2023-02-26 13:38:33,496] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:33,788] {logging_mixin.py:115} INFO - [2023-02-26 13:38:33,782] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:38:33,791] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:33,803] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.312 seconds
[2023-02-26 13:38:40,865] {processor.py:153} INFO - Started process (PID=3281) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:40,866] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:38:40,866] {logging_mixin.py:115} INFO - [2023-02-26 13:38:40,866] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:41,143] {logging_mixin.py:115} INFO - [2023-02-26 13:38:41,138] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:38:41,146] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:41,157] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.295 seconds
[2023-02-26 13:38:44,179] {processor.py:153} INFO - Started process (PID=3283) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:44,180] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:38:44,180] {logging_mixin.py:115} INFO - [2023-02-26 13:38:44,180] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:44,496] {logging_mixin.py:115} INFO - [2023-02-26 13:38:44,476] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:38:44,498] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:38:44,510] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.333 seconds
[2023-02-26 13:39:02,358] {processor.py:153} INFO - Started process (PID=3304) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:02,359] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:39:02,360] {logging_mixin.py:115} INFO - [2023-02-26 13:39:02,360] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:02,629] {logging_mixin.py:115} INFO - [2023-02-26 13:39:02,623] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:39:02,631] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:02,644] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.288 seconds
[2023-02-26 13:39:13,726] {processor.py:153} INFO - Started process (PID=3317) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:13,726] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:39:13,727] {logging_mixin.py:115} INFO - [2023-02-26 13:39:13,727] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:14,000] {logging_mixin.py:115} INFO - [2023-02-26 13:39:13,995] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/function/taxi_availability.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/function/taxi_availability.py", line 3, in <module>
    from helpers.helper import query_file
  File "/opt/airflow/dags/helpers/helper.py", line 3, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-02-26 13:39:14,001] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:14,014] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.291 seconds
[2023-02-26 13:39:32,179] {processor.py:153} INFO - Started process (PID=3329) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:32,179] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:39:32,180] {logging_mixin.py:115} INFO - [2023-02-26 13:39:32,180] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:32,193] {logging_mixin.py:115} INFO - [2023-02-26 13:39:32,193] {dagbag.py:300} INFO - File /opt/airflow/dags/function/taxi_availability.py assumed to contain no DAGs. Skipping.
[2023-02-26 13:39:32,194] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:39:32,209] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.032 seconds
[2023-02-26 13:40:02,421] {processor.py:153} INFO - Started process (PID=3360) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:40:02,421] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:40:02,422] {logging_mixin.py:115} INFO - [2023-02-26 13:40:02,422] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:40:02,428] {logging_mixin.py:115} INFO - [2023-02-26 13:40:02,428] {dagbag.py:300} INFO - File /opt/airflow/dags/function/taxi_availability.py assumed to contain no DAGs. Skipping.
[2023-02-26 13:40:02,428] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:40:02,440] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.022 seconds
[2023-02-26 13:40:32,693] {processor.py:153} INFO - Started process (PID=3392) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:40:32,694] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:40:32,694] {logging_mixin.py:115} INFO - [2023-02-26 13:40:32,694] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:40:32,700] {logging_mixin.py:115} INFO - [2023-02-26 13:40:32,700] {dagbag.py:300} INFO - File /opt/airflow/dags/function/taxi_availability.py assumed to contain no DAGs. Skipping.
[2023-02-26 13:40:32,701] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:40:32,711] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.020 seconds
[2023-02-26 13:41:02,979] {processor.py:153} INFO - Started process (PID=3423) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:41:02,980] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:41:02,980] {logging_mixin.py:115} INFO - [2023-02-26 13:41:02,980] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:41:02,988] {logging_mixin.py:115} INFO - [2023-02-26 13:41:02,988] {dagbag.py:300} INFO - File /opt/airflow/dags/function/taxi_availability.py assumed to contain no DAGs. Skipping.
[2023-02-26 13:41:02,989] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:41:03,001] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.024 seconds
[2023-02-26 13:41:33,256] {processor.py:153} INFO - Started process (PID=3445) to work on /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:41:33,256] {processor.py:641} INFO - Processing file /opt/airflow/dags/function/taxi_availability.py for tasks to queue
[2023-02-26 13:41:33,257] {logging_mixin.py:115} INFO - [2023-02-26 13:41:33,257] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:41:33,263] {logging_mixin.py:115} INFO - [2023-02-26 13:41:33,263] {dagbag.py:300} INFO - File /opt/airflow/dags/function/taxi_availability.py assumed to contain no DAGs. Skipping.
[2023-02-26 13:41:33,263] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/function/taxi_availability.py
[2023-02-26 13:41:33,274] {processor.py:161} INFO - Processing /opt/airflow/dags/function/taxi_availability.py took 0.021 seconds
