[2023-02-26 14:48:33,116] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T14:45:00+00:00 [queued]>
[2023-02-26 14:48:33,123] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T14:45:00+00:00 [queued]>
[2023-02-26 14:48:33,123] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 14:48:33,123] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2023-02-26 14:48:33,123] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 14:48:33,134] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): taxi_api_to_db> on 2023-02-26 14:45:00+00:00
[2023-02-26 14:48:33,139] {standard_task_runner.py:52} INFO - Started process 6528 to run task
[2023-02-26 14:48:33,142] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_taxi_availability', 'taxi_api_to_db', 'scheduled__2023-02-26T14:45:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/get_taxi_availability.py', '--cfg-path', '/tmp/tmpdnd4fyl4', '--error-file', '/tmp/tmp9hv2bnbn']
[2023-02-26 14:48:33,142] {standard_task_runner.py:80} INFO - Job 23: Subtask taxi_api_to_db
[2023-02-26 14:48:33,153] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-02-26 14:48:33,180] {task_command.py:370} INFO - Running <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T14:45:00+00:00 [running]> on host 0337baec7fd8
[2023-02-26 14:48:33,236] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_taxi_availability
AIRFLOW_CTX_TASK_ID=taxi_api_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-26T14:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-26T14:45:00+00:00
[2023-02-26 14:48:33,252] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/taxi_availability.py", line 93, in run_taxi_api_to_db
    db1.run(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 184, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2023-02-26 14:48:33,265] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=get_taxi_availability, task_id=taxi_api_to_db, execution_date=20230226T144500, start_date=20230226T144833, end_date=20230226T144833
[2023-02-26 14:48:33,274] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task taxi_api_to_db (List of SQL statements is empty; 6528)
[2023-02-26 14:48:33,314] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-26 14:48:33,344] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
